import { ArchitectureRule } from '../models/architecture.models';

export const ARCHITECTURE_RULES: readonly ArchitectureRule[] = [
  { id: 'structure-feature-folders', title: 'Feature-oriented folders', category: 'Structure', severity: 'high', description: 'Checks for clear feature boundaries instead of a flat application folder.', whyItMatters: 'Feature boundaries reduce coupling and keep ownership visible as the codebase grows.', recommendation: 'Introduce core, shared, and feature folders with explicit responsibilities.' },
  { id: 'component-size', title: 'Component size', category: 'Components', severity: 'high', description: 'Flags component classes above the configured line threshold.', whyItMatters: 'Large components usually mix orchestration, state, and presentation concerns.', recommendation: 'Extract focused child components and move orchestration into facades or services.' },
  { id: 'service-size', title: 'Service responsibility', category: 'Services', severity: 'high', description: 'Flags oversized services and responsibility-heavy APIs.', whyItMatters: 'Large services become hidden dependency hubs that are difficult to test and replace.', recommendation: 'Split feature-specific services from cross-cutting services.' },
  { id: 'component-naming', title: 'Component naming', category: 'Components', severity: 'low', description: 'Checks that Angular components use the .component.ts suffix.', whyItMatters: 'Predictable naming improves searchability and tooling behavior.', recommendation: 'Rename component files to the conventional .component.ts suffix.' },
  { id: 'service-naming', title: 'Service naming', category: 'Services', severity: 'low', description: 'Checks that injectable services use the .service.ts suffix.', whyItMatters: 'Consistent naming makes responsibilities immediately recognizable.', recommendation: 'Rename injectable service files to the .service.ts suffix.' },
  { id: 'standalone-components', title: 'Standalone component adoption', category: 'Components', severity: 'medium', description: 'Detects components that do not opt into standalone architecture.', whyItMatters: 'Standalone components simplify dependency graphs and route-level loading.', recommendation: 'Migrate declarations incrementally to standalone components.' },
  { id: 'lazy-routes', title: 'Lazy route boundaries', category: 'Routing', severity: 'high', description: 'Checks route definitions for loadComponent or loadChildren.', whyItMatters: 'Route-level splitting controls initial bundle cost as features expand.', recommendation: 'Prefer route-level lazy loading for large feature areas.' },
  { id: 'route-file', title: 'Dedicated route configuration', category: 'Routing', severity: 'medium', description: 'Checks for app.routes.ts or feature routing files.', whyItMatters: 'Explicit route configuration keeps navigation architecture reviewable.', recommendation: 'Define routes in dedicated, typed route configuration files.' },
  { id: 'nested-subscribe', title: 'Nested RxJS subscriptions', category: 'RxJS', severity: 'high', description: 'Detects subscribe calls nested inside other subscriptions.', whyItMatters: 'Nested subscriptions create race conditions and fragmented teardown logic.', recommendation: 'Replace nested subscriptions with switchMap, combineLatest, or signal-based state.' },
  { id: 'manual-subscriptions', title: 'Manual subscription lifecycle', category: 'RxJS', severity: 'medium', description: 'Flags repeated subscribe calls without an observable teardown pattern.', whyItMatters: 'Unmanaged subscriptions can leak and continue updating destroyed views.', recommendation: 'Use takeUntilDestroyed, async pipe, or toSignal for view-bound streams.' },
  { id: 'signals-adoption', title: 'Signals adoption', category: 'Signals', severity: 'low', description: 'Measures signal, computed, effect, input, output, and model usage.', whyItMatters: 'Signals make local reactive state explicit and reduce subscription overhead.', recommendation: 'Prefer signals for synchronous local state and derived view models.' },
  { id: 'state-scattering', title: 'State ownership', category: 'State Management', severity: 'medium', description: 'Looks for state spread across numerous mutable services.', whyItMatters: 'Unclear state ownership increases coupling and inconsistent updates.', recommendation: 'Assign state to feature facades and expose read-only reactive APIs.' },
  { id: 'hardcoded-secrets', title: 'Hardcoded secrets', category: 'Security', severity: 'critical', description: 'Detects likely API keys, tokens, passwords, or secrets in source files.', whyItMatters: 'Frontend source is public to every application user.', recommendation: 'Remove secrets from client code and rotate any exposed credentials.' },
  { id: 'console-log', title: 'Production console logging', category: 'Maintainability', severity: 'low', description: 'Finds console.log statements in production source.', whyItMatters: 'Unstructured logs leak context and add noise during incident analysis.', recommendation: 'Remove debug logging or route it through an environment-aware logger.' },
  { id: 'any-usage', title: 'Explicit type safety', category: 'Maintainability', severity: 'medium', description: 'Counts explicit any usage above the configured threshold.', whyItMatters: 'Any silently removes compiler guarantees across dependency boundaries.', recommendation: 'Replace any with domain types, unknown, or validated generic constraints.' },
  { id: 'todo-comments', title: 'Tracked technical debt', category: 'Maintainability', severity: 'low', description: 'Counts TODO, FIXME, and HACK comments.', whyItMatters: 'Untracked inline debt tends to outlive its original context.', recommendation: 'Convert actionable debt into owned work items and remove stale comments.' },
  { id: 'testing-ratio', title: 'Test coverage signal', category: 'Testing', severity: 'high', description: 'Compares source files with colocated specification files.', whyItMatters: 'A weak test signal makes architecture changes slower and riskier.', recommendation: 'Prioritize tests at service, route, and high-value component boundaries.' },
  { id: 'template-tracking', title: 'Tracked template loops', category: 'Performance', severity: 'medium', description: 'Detects loops that may be missing track or trackBy.', whyItMatters: 'Tracking prevents unnecessary DOM recreation during list updates.', recommendation: 'Add stable track expressions for every repeated template collection.' },
  { id: 'legacy-ngmodules', title: 'Legacy NgModule weight', category: 'Structure', severity: 'medium', description: 'Detects NgModule-heavy architecture.', whyItMatters: 'Large module graphs obscure dependencies and hinder route splitting.', recommendation: 'Move new code to standalone APIs and migrate legacy modules by feature.' },
  { id: 'barrel-exports', title: 'Barrel export depth', category: 'Maintainability', severity: 'low', description: 'Flags excessive index.ts barrel files.', whyItMatters: 'Deep barrels hide dependency direction and can create circular imports.', recommendation: 'Use explicit imports at architectural boundaries.' }
];
